### ISSUE TITLE
How can I sign the CLA?

### ISSUE THREAD

**Issue by RichardLitt** [catalyst-network/Community#6]
The README mentions it, but I'm not sure how to find it.

**Comment by nshCore** [comment]
@RichardLitt it's an automated github bot that will comment on PR's over a certain size.

@stxphxn have you deployed the CLA container yet?

**Comment by nshCore** [comment]
> @nshCore Shouldn't it ping for anyone who has done any contributions? Is this turned on for all repositories?

it's using our install of https://cla-assistant.io, it has a threshold for when it kicks in, I don't want to make people sign it for small type changes or little additions/ fixes

**Comment by RichardLitt** [comment]
Is it enabled for all repositories?

**Comment by nshCore** [comment]
> Is it enabled for all repositories?

it's only enabled on some repositories specifically the gpl repos
